### ISSUE TITLE
 "kintone-cli dev --watch" does not work on Windows. When developing plugins.

### ISSUE THREAD

**Issue by Yanchi4425** [kintone/kintone-cli#15]
When developing plugins on Windows, using the "--watch" option with the "kintone-cli dev" command does not reflect the changes.

If you save the jsx file, it will be watched and the build will run, but the changes will not be reflected on the kintone screen.

On macOS, the exact same project is successfully reflected.

My Env:

- OS: Windows 10 Pro x64
- Node.js : v12.16.1
- kintone-cli : v0.1.3

**Comment by youtr-s** [comment]
Sorry to the late reply.
We will survey this problem. 
Please wait a while.

**Comment by Yanchi4425** [comment]
I did a little verification on my own.

Projects created on macOS, will working on windows.
I haven't yet compare how they differ.

**Comment by cy-hirayama** [comment]
We confirmed same phenomenon at Windows10.
We think that the problem is solved  by below.
(Browser let Kintone customization do to trust)
https://github.com/kintone/kintone-cli/blob/master/quickstart.md#4-start-dev

Have you had a chance to do this?

**Comment by Yanchi4425** [comment]
Hi.
I have not solved yet.

Which version of kintone-cli are you using?

By the way, I installed kintone-cli again globally with the following command.
``` npm install -g git://github.com/kintone/kintone-cli.git ```

But ```kintone-cli --version``` returns "0.1.2."

**Comment by cy-hirayama** [comment]
I useing version of kintone-cli is "0.1.3"

>By the way, I installed kintone-cli again globally with the following command.
>npm install -g git://github.com/kintone/kintone-cli.git
>
>But kintone-cli --version returns "0.1.2."

I confirmed same phenomenon.
I think it is Bug.

Could you confirm anything displayed on console?

**Comment by Yanchi4425** [comment]
@cy-hirayama 

The output on my console looks like this:
```
C:\Users\xxx>npm --version
6.13.4

C:\Users\xxx>node --version
v12.16.1
```
```
C:\Users\xxx>npm uninstall -g kintone-cli
removed 53 packages in 2.73s

C:\Users\xxx>npm install -g git://github.com/kintone/kintone-cli.git
C:\Program Files\nodejs\kintone-cli -> C:\Program Files\nodejs\node_modules\kintone-cli\dist\index.js
+ kintone-cli@0.1.3
added 53 packages from 41 contributors in 26.923s
```

```
C:\Users\xxx>kintone-cli --version
0.1.2
```

It seems that v0.1.3 is installed, but the version is displayed as v0.1.2.

**Comment by cy-hirayama** [comment]
Thank you for your confirmation.
I executed same command and could confirm same result.
But My environment can execute "kintone-cli dev" with " --watch" mode at Windows10.

Could you confirm console by using developer tool in browser while you run "kintone-cli dev" with " --watch" mode?

**Comment by Yanchi4425** [comment]
I apologize for the delay in replying.

Once I uninstalled Node.js and k-cli and put them back in, it worked fine.
It was a problem in myenvironment.

Thank you for your support in your busy time.
